### ISSUE TITLE
exception on data export from gee

### ISSUE THREAD

**Issue by philosadelphos** [nasa/LHASA#8]
Greetings,
I've got the following error data export from gee (what could be the problem?):

Earth Engine initialized. 

pfdf_export_2022_07_04T0950 succeeded.
total runtime: 0.7613542230555556 hours
Downloading pfdf_export_2022_07_04T0950...
Could not download file pfdf_export_2022_07_04T0950

The following exception occured: (<class 'ee.ee_exception.EEException'>, EEException("Collection.loadTable: Collection asset 'users/<USER_ID>/pfdf_basin_assets/pfdf_export_2022_07_04T0950' not found."), <traceback object at 0x7f35731d6040>

**Comment by thomasastanley** [comment]
Are you on the master or dev branch?

**Comment by eorland** [comment]
Hello - thanks for raising this issue. A few quick questions: if you pull up the manual code editor at https://code.earthengine.google.com/, do you see the asset listed there? I also assume you replaced your user id with the text ````<USER_ID>````, but I would double check to make sure that your are inputting your user id correctly when you run the the querying tool. Keep me posted and happy to keep troubleshooting from there.

**Comment by philosadelphos** [comment]
> Are you on the master or dev branch?

Hi thomas
I'm on the master.

**Comment by philosadelphos** [comment]
> Hello - thanks for raising this issue. A few quick questions: if you pull up the manual code editor at https://code.earthengine.google.com/, do you see the asset listed there? I also assume you replaced your user id with the text `<USER_ID>`, but I would double check to make sure that your are inputting your user id correctly when you run the the querying tool. Keep me posted and happy to keep troubleshooting from there.

Hi eorland,
Indee, I see in gee assets (users/<USER_ID>/pfdf_basin_assets/pfdf_export_2022_07_04T0950) besides previous assets processed before.  Yes, I've replaced USER_ID. But, if it is important, I can share the archived asset at gee. I just didn't figure it out, how to download the processed data (and eventually use in qgis platform)
 
Also in my laptop <PATH_TO_FOLDER>/LHASA/archive/asset_downloads/pfdf_export_2022_07_04T0950 , although automatically generated the folder assets, it didn't store anything? Is it normal?

**Comment by philosadelphos** [comment]
I've detected that I can't create any cloud project in gee. In the left panel of gee, I've this info: «CLOUD ASSETS:
You haven't selected any Cloud Projects yet. Click "Add A Project" to access or upload assets.» Although, I do have acces to my  LEGACY ASSETS in the same panel, where one of the following processing results is available in the provided form, please check the results here:
https://code.earthengine.google.com/?asset=users/up201804418/pfdf_basin_assets/pfdf_export_2022_07_04T0950

**Comment by thomasastanley** [comment]
@philosadelphos I don't think we can take a look at this until next week.

**Comment by philosadelphos** [comment]
Hi @thomasastanley, thanks for the input. Totally ok. I has just testing this tool. Just shared this feedback to let you know about possible bugs. All the best.

**Comment by eorland** [comment]
Closing this because we have a new version on the way that no longer uses Earth Engine.

**Comment by eorland** [comment]
Closing this because we have a new version on the way that no longer uses Earth Engine.

**Comment by thomasastanley** [comment]
@philosadelphos This has been fixed by #14
